### PR TITLE
Re-architect JSBSim scenario loading

### PR DESCRIPTION
**Pull request by mvacanti**
This proposed change re-architects the way that models and scenarios are loaded and handled. Specifically this allows the user to load a JSBSim script that drives conditional behavior. An engine failure scenario has been included as a demonstration, JSBSim will fail motor 0 when the aircraft reaches an altitude of 425 m above sea level. A simple way to test is takeoff and climb at least 20 m above the ground to observe the effect (the aircraft will lose control).

`make px4_sitl jsbsim_quadrotor_x__quadrotor_x.motor_fail.LSZH`

Other changes include simplifying model directory.

**IMPORTANT:** 

Revise the following files (outside the scope of this repo):
_**sitl_target.cmake**_
Lines 180 and 181:
``set(models_jsbsim none quadrotor_x hexarotor_x rascal )``
``set(worlds_jsbsim none quadrotor_x.LSZH quadrotor_x.motor_fail.LSZH hexarotor_x.LSZH rascal.LSZH)``

**_setup_jsbsim.bash_**
Lines 22 and 23:
            `AIRCRAFT_DIR="rascal"`
            `MODEL_NAME="rascal"`
Note this script could likely be removed with the directory simplification.

**_sitl_run.sh_**
Line 166:
`	"${build_path}/build_jsbsim_bridge/jsbsim_bridge" "models/${JSBSIM_AIRCRAFT_DIR}" $JSBSIM_AIRCRAFT_MODEL ${model} "${src_path}/Tools/jsbsim_bridge/scenario/${world}.xml" $HEADLESS 2> /dev/null &`

### CODE REVIEW

**Comment by mvacanti** [comment]
@Jaeyoung-Lim [new commit](https://github.com/PX4/px4-jsbsim-bridge/pull/7/commits/6a2bf7be0f267ab042f98f3b68112f64e784e7f3) based on feedback:

This proposed change re-architects the way that models and scenarios are loaded and handled. Specifically this allows the user to load a JSBSim script that drives conditional behavior. An engine failure scenario has been included as a demonstration, JSBSim will fail motor 0 when the aircraft reaches an altitude of 425 m above sea level. A simple way to test is takeoff and climb at least 20 m above the ground to observe the effect (the aircraft will lose control).

`export SCENARIO=motor_0_fail`

`make px4_sitl jsbsim_quadrotor_x`

I have not been able to identify a mechanism for JSBSim to load an airframe with a different directory / filename e.g. Rascal/Rascal-110JSBSim using the script definition method and so this has been simplified / removed - seems to be a restriction of JSBSIm but open to inputs.

Only requires update to [`sitl_run.sh`](https://github.com/mvacanti/Firmware/blob/pr-update-sitl_run-jsbsim-script-loading/Tools/sitl_run.sh)

Removes need for `setup_jsbsim.bash`

**Comment by Jaeyoung-Lim** [comment]
@mvacanti Thanks for the improvements!

Regarding 
> I have not been able to identify a mechanism for JSBSim to load an airframe with a different directory / filename e.g. Rascal/Rascal-110JSBSim using the script definition method and so this has been simplified / removed - seems to be a restriction of JSBSIm but open to inputs.

It seems to conflict slightly with what I have been doing in https://github.com/Auterion/px4-jsbsim-bridge/pull/10 . Could you maybe review https://github.com/Auterion/px4-jsbsim-bridge/pull/10 and we could discuss on how we can merge the two.

**Comment by mvacanti** [comment]
@Jaeyoung-Lim I looked at the Auterion#10 and think it is a significant improvement on a number of different issues including scaling the XML parsing and general structure that can be merged.

The problem that I am seeing with JSBSim is the following: 
```bash
Could not open file: Path "/home/user/Firmware/Tools/jsbsim_bridge/models/Rascal/Rascal110-JSBSim/Rascal110-JSBSim.xml"
  JSBSim failed to open the configuration file: Path "/home/user/Firmware/Tools/jsbsim_bridge/models/Rascal/Rascal110-JSBSim/Rascal110-JSBSim.xml"
```

The issue is that JSBSim is introducing an additional **/Rascal110-JSBSim/** where we expect none. I traced this to the specific code in JSBSim that loads the aircraft as a part of the script loading [here:](https://github.com/JSBSim-Team/jsbsim/blob/b42f4238880ae1729acd55894381f74a0fe1ca13/src/input_output/FGScript.cpp#L156-L165) 

```cpp
  element = document->FindElement("use");
  if (element) {
    aircraft = element->GetAttributeValue("aircraft");
    if (!aircraft.empty()) {
      if (!FDMExec->LoadModel(aircraft))
        return false;
    } else {
      cerr << "Aircraft must be specified in use element." << endl;
      return false;
    }
```
Tracing the LoadModel we see that this behavior is expected and anticipated [here](https://github.com/JSBSim-Team/jsbsim/blob/b42f4238880ae1729acd55894381f74a0fe1ca13/src/FGFDMExec.cpp#L688-L690):

```cpp
  FullAircraftPath = AircraftPath;
  if (addModelToPath) FullAircraftPath.append(model);
  aircraftCfgFileName = FullAircraftPath/(model + ".xml");
```
This does not manifest itself when loading JSBSim using an aircraft and initialization file because the airframe loading is handled in a different function that does not append the additional directory by setting the `addModelToPath = FALSE ` [here:](https://github.com/PX4/px4-jsbsim-bridge/blob/a14e6cc27f26f926b9bf5550ddefc29394a2af84/src/main.cpp#L71)

```cpp
    fdmexec->LoadModel(argv[2], false);
```
With this information I see that we have a few options: 
1. Create a separate fork of JSBSim for PX4 and make the modification to set `addModelToPath = FALSE ` for the script loading.
2. Do some dynamic file allocation during run such that the files and directories exist as expected by JSBSim
3. Simplify the file structure as previously proposed
4. or ?

Appreciate thoughts and inputs.

**Comment by mvacanti** [comment]
@Jaeyoung-Lim see the proposed modification to enable desired JSBSim behavior for script loading [here](https://github.com/mvacanti/jsbsim/tree/pr-enable-script-model-to-path). This will allow us to merge [Auterion#10](https://github.com/Auterion/px4-jsbsim-bridge/pull/10)  and get the desired behavior but will require a separate fork and / or coordinating with the JSBSim team to get it merged (does not affect the nominal configuration or performance of JSBSim).

**Comment by mvacanti** [comment]
This PR has been moved to https://github.com/Auterion/px4-jsbsim-bridge/pull/18

**Pull request closed without merging**
